{% set name = "pipdate" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26bd12075e63ef7f8094da36c27bf5539d298f4ef2af6acba20e98b502439d6d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - requests

test:
  imports:
    - pipdate

about:
  home: https://github.com/nschloe/pipdate
  license: MIT
  license_family: MIT
  license: LICENSE
  summary: 'pipdate is a collection of small pip update helpers'

extra:
  recipe-maintainers:
    - hmaarrfk
