{% set name = "pipdate" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b6b7ec2c5468fb7036ec9d6b2ced7a8a538db55aaca03f30199216d3bbd264b

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - appdirs
    - requests
    - importlib_metadata
    - rich
    - setuptools
    - packaging

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - pipdate

about:
  home: https://github.com/nschloe/pipdate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pipdate is a collection of small pip update helpers

extra:
  recipe-maintainers:
    - hmaarrfk
