{% set name = "pipdate" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 240c0f270ddb7470ad7b8c8fba4106e3dbd8817a370624fd8c32cf19155c9547

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - requests

test:
  imports:
    - pipdate

about:
  home: https://github.com/nschloe/pipdate
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'pipdate is a collection of small pip update helpers'

extra:
  recipe-maintainers:
    - hmaarrfk
