travis:
  secure:
    BINSTAR_TOKEN: IWLNBGCmZb67gGPyYB+BAFEriyAUzAxe7nMBnyOY2Fz39ywMfgQRxt7mUr8U4yDGIrAG7dub/8w4jU7vnR9VZqB3fzCz5ohjPLTwtvHJG9J5h0fchPDjc5FaTSds/pxInDIPm6z2o0+n3CACPfGWLKF0nK2DWjDKB9SauCEZydGHxZZviGxBNR8F55zgp+K2o07R7+hNCSpLHppEOtouFkbAArM2ljWX4lT5xaLPDM8laJ/IQcCpJy/IGV6c9OJlU8zSTaManSmtgmDgNGIqmNnSx5AnTIiPLgShW7DR25CV9C37gVgkdeBH4QT60gApi1OtfAHlVFWqNE8ZI31NBFaVT4HuVJQ2xKoEjRczu5AvD/LxusfRCJ9eEiAYV0ip9sIxhhiY+QhUeaxUOQ35n4qPltDslWQHXMiD+WoIfqUA9ewK2kwUXkv7GVM2ecYH57CPZTJSoCD7P6pLzcKOPZLeGnqkX/ufin0cwyhP6ua9G/mL3AfQsiUabS+d5qqfQSLsONSB1W0PnBBYzv8uJZIWCdEjYB3PY8KL5tDFhae9jQJpdAIYHAisDb5icNf16chXnt4Nl9Bryk3nRLCjhjmndrGRos97GP/H8R42lLwy6DclX677j21nmoDnrKVP2nVbFYTCgGPkrUBFve2PmsQDYfrWB1lf+CQ41Q29qpU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
